[project]
name = "chainlit-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.4.1",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.4",
]

[project.scripts]
start = "hello:run"
